# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_image_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
