# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_auto_20190228_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
    ]
